name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4
        pip install requests
    - name: run script and deploy
      run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com" && git config --global user.name "github-actions[bot]" && git config --global push.default "matching" && git clone -b output "https://${{ secrets.REPOKEY }}@github.com/zoreu/kodiservice.git" && wget https://raw.githubusercontent.com/zoreu/kodiservice/main/cx.py && python cx.py && git add cx.json && git commit -m "Publishing revision $(git --git-dir ../.git rev-parse --short HEAD)" && git push --force origin output



          
